/*
* Date:2020/7/28
* author:lwb
* Desc:
*/
List billData = [
  {
    "title": "餐饮",
    "url": "ic_home_item_buycar.png",
    "rightStr": "¥598.98",
    "time": "2020年07月12日 星期日",
    "timeFm": "07月12日",
    "isShowTitle": false,
  },
  {
    "title": "交通",
    "url": "ic_home_item_car.png",
    "rightStr": "¥1,298.98",
    "time": "2020年07月12日 星期日",
    "timeFm": "07月12日",
    "isShowTitle": false,
  },
  {
    "title": "出行",
    "url": "ic_home_item_food.png",
    "rightStr": "¥59,998.98",
    "time": "2020年07月14日 星期二",
    "timeFm": "07月14日",
    "isShowTitle": false,
  },
  {
    "title": "骑车",
    "url": "ic_home_item_buycar.png",
    "rightStr": "¥1,000.98",
    "time": "2020年07月15日 星期三",
    "timeFm": "07月15日",
    "isShowTitle": false,
  },
  {
    "title": "购物",
    "url": "ic_home_item_car.png",
    "rightStr": "¥100,100.98",
    "time": "2020年07月15日 星期三",
    "timeFm": "07月15日",
    "isShowTitle": false,
  },
  {
    "title": "娱乐",
    "url": "ic_home_item_food.png",
    "rightStr": "¥2.98",
    "time": "2020年07月15日 星期三",
    "timeFm": "07月15日",
    "isShowTitle": false,
  },
  {
    "title": "文教",
    "url": "ic_home_item_buycar.png",
    "rightStr": "¥1.00",
    "time": "2020年07月17日 星期五",
    "timeFm": "07月17日",
    "isShowTitle": false,
  },
  {
    "title": "育儿",
    "url": "ic_home_item_car.png",
    "rightStr": "¥4.20",
    "time": "2020年07月17日 星期五",
    "timeFm": "07月17日",
    "isShowTitle": false,
  },
  {
    "title": "通讯",
    "url": "ic_home_item_buycar.png",
    "rightStr": "¥900.18",
    "time": "2020年07月19日 星期日",
    "timeFm": "07月19日",
    "isShowTitle": false,
  },
  {
    "title": "住房",
    "url": "ic_home_item_food.png",
    "rightStr": "¥598.00",
    "time": "2020年07月27日 星期一",
    "timeFm": "07月27日",
    "isShowTitle": false,
  },
  {
    "title": "零食",
    "url": "ic_home_item_buycar.png",
    "rightStr": "¥5.50",
    "time": "2020年07月27日 星期一",
    "timeFm": "07月27日",
    "isShowTitle": false,
  },
];
